### ISSUE TITLE
Cameraネームスペースの実装

### ISSUE THREAD

**Issue by Tait41** [DevelopSquare/3dBoardGame#5]
・仕様変更
・README.md作成

**Comment by takahashi1130** [comment]
<img width="1147" alt="example" src="https://user-images.githubusercontent.com/57855627/76679335-fd21e680-6622-11ea-9e24-394c598dc3c5.png">

**Comment by takahashi1130** [comment]
再オープン

**Comment by takahashi1130** [comment]
機能はできていたが使い方がわかりずらかったので、使える形に修正
README.md作成
